Feature/12 feat 사진 팝업 제작
pknu-wap/Dokdo_Public pull request #13
Opened 2024-10-10 12:18 UTC by khw010419

### #️⃣ Related Issue
> #12

### 📝 Work Detail

> Stage3의 벽 사진 구현 및 모달 기능 구현
 STAGE3의 벽에 임의의 사진 넣기(전체합쳐진 사진) (10/10)
 사진을 눌렀을 때 팝업 뜨게 하기 (10/10)
 팝업안에 사진 구현 (10/10)

### ScreenShots (선택)
![스크린샷(47)](https://github.com/user-attachments/assets/34497c0d-56b8-4b24-bc20-91576da8002d)
> 사진 구현

![스크린샷(48)](https://github.com/user-attachments/assets/18ae7bbc-5286-447f-9aff-1c2ff613fb95)
> 사진 눌렀을 때 모달 뜨게 구현
![스크린샷(49)](https://github.com/user-attachments/assets/ca0daf40-fb06-41b8-8dab-f251360c98b3)
> 친일파 사진 눌렀을 때 눌렀다는 표시 되게 구현

### 💬 Review Requirements

> merge하고 싶어요!

2024-10-10 12:29 UTC, aranlll reviewed
옥 사진 하나하나 넣느라 진짜 힘들엇겟는데요..?! 코드 짜느라 수고해써요!!!!

2024-10-10 12:47 UTC, aranlll commented on client/src/components/Modal.module.css
> +  top: 900%;
여기 900% 말구용 !!

2024-10-10 12:55 UTC, Keun04 requested changes
css 수정사항

2024-10-10 12:55 UTC, Keun04 commented on client/src/components/Modal.module.css
> +  top: 900%;
이렇게 공용 컴포넌트 css 수정하면 모달창을 사용하는 다른 화면에서는 엄청 밑에서 모달창이 뜰 것 같아요!

2024-10-10 12:55 UTC, Keun04 commented on client/src/pages/StartPage.module.css
> +
제 페이지 css에 왜 엔터치셨나요?ㅋㅋㅋ

2024-10-29 11:49 UTC, Keun04 approved these changes

2024-10-29 11:49 UTC, merged